project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Addressing Disparities Across Pennsylvania Counties"
  page-footer:
    left: "macyt@upenn.edu | rswett01@upenn.edu"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    logo: "/kmeans.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/MUSA-550-Fall-2024/
        text: "MUSA 550 GitHub"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Project Overview
      - description.qmd 
      - section: analysis/index.qmd
        contents:
          - analysis/Data_Preprocess.ipynb 
          - analysis/ESDA.ipynb
          - analysis/kmeans.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    default: true
